### ISSUE TITLE
mismatch between encrypt and decrypt

### ISSUE THREAD

**Issue by C0okiesnCream** [C0okiesnCream/group-chat-encryptor#1]
ex. typed [ ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz 1234567890 !?#$[]{}
got this [ [ ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqratuvwxyz 1234567890 !?#$[]{}
brackets are for enlignment
looks like its just a and s for this key but some get messed up a lot more, might have to check through KEYBASE on both and check if i got anything wrong, also should compare the c loops

**Comment by C0okiesnCream** [comment]
sorry the open and close of this were from a misclick

**Comment by EmersonJorgyCreate** [comment]
The List 'KEYBASE' Is the same. The **_ERROR_** must be in the if-else statements.

**Comment by C0okiesnCream** [comment]
I have found the duplicates!

**Comment by C0okiesnCream** [comment]
there are duplicate "~" on line 92-93 in both encrypt and decrypt, which means there must be an absent tilda in keygen

**Comment by C0okiesnCream** [comment]
nevermind, they do exist in keygen, but there is an extra "/" in keygen, line 87

**Comment by C0okiesnCream** [comment]
if we remove this it should fix everything, but we'll see

**Comment by C0okiesnCream** [comment]
nevermind, the slash is on line 87 in encrypt and decrypt, which should actually be encode and decode, anyways, we want to remove the slash on line 84 instead

**Comment by C0okiesnCream** [comment]
so _that_ should fix **everything**
